### PR TITLE
Migration to BeatmapsIO API on BeatSaver

### PR DESCRIPTION
**Pull request by EnderdracheLP**
This should hopefully contain all the new API end points, I might have missed some or not implemented some, because documentation seems to differ from the actual result given on request in some places.

Stuff done:
- [x] Add user specific endpoints
- [x] Add user stats classes
- [x] Fix any bugs/crashes that could still exist
- [x] Fix crash when searching for "reaxt"
- [x] Add exception handling
- [x] Add BeastSaberAPI
- [x] Add ScoreSaberAPI

### CODE REVIEW

**Comment by EnderdracheLP** [comment]
Just found another crash while searching for songs, need to investigate

**Comment by EnderdracheLP** [comment]
All crashes should be solved now, didn't find another crash so far

**Comment by EnderdracheLP** [comment]
Idk what the thing is with the optional tesplay bool, as I haven't seen it being included anywhere which makes it weird that it crashes

**Comment by EnderdracheLP** [comment]
Oh, god I hope this thing no longer crashes anywhere, now with exception handling it should at least just display an error

**Review by darknight1050 — APPROVED** [review]

**Pull request merged**
